services:
  keycloak.api:
    image: ${DOCKER_REGISTRY-}keycloakapi
    build:
      context: .
      dockerfile: Keycloak.IdentityServer/Keycloak.Api/Dockerfile
      
  identitydb:
    image: postgres:alpine

  # keycloak.server:
  #   image: quay.io/keycloak/keycloak:24.0.3

  keycloak.server.byhand:
    image: quay.io/keycloak/keycloak:latest

  jaeger.open.telemetry:
    image: jaegertracing/all-in-one:latest

  keycloak.gateway:
    image: ${DOCKER_REGISTRY-}keycloakgateway
    build:
      context: .
      dockerfile: Keycloak.Gateway/Dockerfile

volumes:
  postgres_identity:

