services:
  keycloak.api:
    image: ${DOCKER_REGISTRY-}keycloakapi
    build:
      context: .
      dockerfile: Keycloak.IdentityServer/Keycloak.Api/Dockerfile

  keycloak.server:
    image: quay.io/keycloak/keycloak:24.0.3
